version: '3.8'

services:
  bot:
    build: .
    container_name: fuelgraph_bot
    restart: always
    env_file:
      - ".env"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: fuelgraph_mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
