version: '3.8'

services:
  bot:
    build: .
    container_name: fuelgraph_bot
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: fuelgraph_mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
